name: OwnBlocks
main: me.cvenomz.OwnBlocks.OwnBlocks
version: 10.0
author: cvenomz
commands:
  ownblocks:
    aliases: [ob]
    description: toggle per-player OwnBlocks activation
    usage: /<command>
